From ubuntu:latest

WORKDIR /db-init

RUN apt-get update -y

RUN apt install -y jq

RUN apt-get install -y python3-pip

COPY ./requirements.txt .

RUN pip3 install -r requirements.txt

COPY ./initiate-db.sh .

ENTRYPOINT ["./initiate-db.sh"]