name: Airport API CD
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-west-2
    steps:
    - uses: actions/checkout@v2
    - name: Zip lambda functions
      working-directory: terraform
        run: ./package-lambda-functions.sh  
    - name: Deploy aws resources
      working-directory: terraform/infra
      run: |
        terraform init
        terraform apply -auto-approve
    - name: Initiate DynamoDB Airport data
      working-directory: terraform/remote-db-initiator
      run: |
        ./initiate-db.sh