# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Airport API CI

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up DynamoDB Local
      uses: rrainn/dynamodb-action@v2.0.1
      with:
        port: 8000
        cors: '*'
    - name: Initialise DynamoDB Local
      run: |
        cd local-db-initiator
        ./create-local-db.sh
      env:
        AWS_DEFAULT_REGION: "fake-region"
        AWS_ACCESS_KEY_ID: "key_id"
        AWS_SECRET_ACCESS_KEY: "key"
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Build app
      run: |
        cd lambda
        if [ -f journey-requirements.txt ]; then pip install -r journey-requirements.txt; fi
        ./run.sh &
      env:
        AWS_DEFAULT_REGION: "fake-region"
        AWS_ACCESS_KEY_ID: "key_id"
        AWS_SECRET_ACCESS_KEY: "key"
    - name: Test with pytest
      run: |
        sleep 10
        cd tests/
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python3 test-endpoint.py
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Validate Terraform
        run: terraform validate

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/terraform-github-actions@v2.0.0
      with:
        tf_actions_version: 0.13.5
        tf_actions_subcommand: apply
        tf_actions_working_dir: terraform/infra
